# SPDX-License-Identifier: MIT
# Deterministic linking on Windows (A-05): /Brepro drops the PE timestamp
# so back-to-back release builds bit-match (PDBs still differ — compare
# the .exe only, see scripts/verify-repro.ps1).
[target.'cfg(windows)']
rustflags = ["-C", "link-arg=/Brepro"]
