# SPDX-License-Identifier: MIT
# Builds THIRD-PARTY.md from `cargo license` TSV output (Z-09).
# Run: powershell -ExecutionPolicy Bypass -File scripts/gen-third-party.ps1
$ErrorActionPreference = "Stop"
$Repo = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$tmp = Join-Path ([System.IO.Path]::GetTempPath()) "flowvoice-licenses.tsv"
& cargo license --features audio,gui -t -o $tmp
if ($LASTEXITCODE -ne 0) { throw "cargo license failed" }
$enc = New-Object System.Text.UTF8Encoding($false)
$w = New-Object System.IO.StreamWriter((Join-Path $Repo "THIRD-PARTY.md"), $false, $enc)
$w.WriteLine("# Third-party dependency licenses")
$w.WriteLine("")
$w.WriteLine("Generated by `scripts/gen-third-party.ps1` (`cargo license --features audio,gui`).")
$w.WriteLine("Project license: MIT. Dual-licensed crates are used under their permissive option")
$w.WriteLine("(Apache-2.0/MIT); `option-ext` (MPL-2.0, unmodified, non-Windows only) is covered by")
$w.WriteLine("the MPL-2.0 notice requirement via this file.")
$w.WriteLine("")
$w.WriteLine("| crate | version | license | repository |")
$w.WriteLine("|---|---|---|---|")
foreach ($line in [System.IO.File]::ReadAllLines($tmp)) {
    if ($line.StartsWith("name`t")) { continue }
    $f = $line -split "`t"
    if ($f.Count -lt 5 -or [string]::IsNullOrWhiteSpace($f[0])) { continue }
    $repo = if ([string]::IsNullOrWhiteSpace($f[3])) { "-" } else { $f[3] }
    $w.WriteLine(("| {0} | {1} | {2} | {3} |" -f $f[0].Trim(), $f[1].Trim(), $f[4].Trim(), $repo.Trim()))
}
$w.Close()
Remove-Item -LiteralPath $tmp -ErrorAction SilentlyContinue
Write-Host "THIRD-PARTY.md updated"
